### ISSUE TITLE
mke2fs permissions

### ISSUE THREAD

**Issue by venitp** [tytso/e2fsprogs#23] opened 2019-09-18 17:11 UTC
When a new inode is created here:
https://github.com/tytso/e2fsprogs/blob/master/misc/create_inode.c#L125
don't OR the mode with a default value, but assign the original value as intended. With the OR in place all folders get write permissions set for the owner regardless of permissions of the origin folder.

Test:
$ mkdir -p rootfs/test
$ chmod 555 ./rootfs/test
$ sudo mke2fs -t ext4 -d rootfs rootfs.ext4 4096
...
$ sudo debugfs -R "ls -p /" rootfs.ext4 | grep test
/12/040**755**/1000/1000/test//

**Comment by leojrfs** [comment] 2019-09-19 13:09
Same issue here with `e2fsprogs` `1.44.5` (buildroot) and `1.44.1-1ubuntu1.1` (ubuntu 18.04)

**Comment by tytso** [comment] 2019-09-19 13:53
Your proposed fix is not correct.   You can't just override the mode bits because the high bits are used to specify the file type (e.g., directory, symbolic link, etc.)     The issue is that fs->umask defaults to 022, and in mke2fs's create_lost_and_found() function, it gets set to 077.

The right is fix is likely adding a "save_umask = fs->umask; fs->umask = 0" to populate_fs2(), and then restoring fs->umask at the end of that function.

**Comment by venitp** [comment] 2019-09-19 16:30
Hi tytso

Many thanks for your quick response. I think `lstat()` called here:
https://github.com/tytso/e2fsprogs/blob/master/misc/create_inode.c#L823
will already output a full set of permissions along with the type and all the flags: SUID, sticky bit etc. I don't think you have to use umask here, as the created inode has to follow the origin, not umask setting.

It doesn't mean that your fix isn't good, it will work as well. However I think removing the OR is just simpler&cleaner solution, than having to OR with temporarily zeroed umask.

**Comment by tytso** [comment] 2019-09-19 19:33
Technically what we should be doing is mapping S_IFBLK to LINUX_S_IFBLK, S_IRUSR to LINUX_S_IRUSR, etc.    All the world is not Linux, and assuming we can take the value from st_mode returned from lstat(2) and shove it into ext2 inode.   POSIX does not mandate a specific encoding of S_IFBLK, S_IRUSR, etc., for MacOS, Windows, etc.       What we currently have in misc/create_inode.c is not correct, but neither is just assigning directly into it.

**Comment by venitp** [comment] 2019-09-23 13:29
Many thanks for your replies tytso, let me leave the support for other OSes with you then.
Cheers

**Comment by leojrfs** [comment] 2020-07-15 15:45
I can confirm that this is no longer an issue in the latest stable version.

I guess it was fixed in f106b01c98d7abc12af39aad4024f17ffa14dc06?

**Comment by tytso** [comment] 2021-01-29 22:48
Yes, this should be fixed now.

**Closed by tytso** 2021-01-29 22:48 UTC
