### ISSUE TITLE
inode size for small filesystems and 2038

### ISSUE THREAD

**Issue by jluebbe** [tytso/e2fsprogs#54] opened 2020-11-11 11:42 UTC
The default mke2fs.conf set an inode size of 128 for 'small' filesystems (also for floppy and hurd):
https://github.com/tytso/e2fsprogs/blob/7b8253ba09e635d328a48c98a184b571b809911b/misc/mke2fs.conf.in#L19

mke2fs regards filesystems smaller than 512MB as 'small', which leads a default inode size of 128 on embedded systems (where such sizes are still relatively common) and boot partitions on PCs. This in turn results in a kernel warning of "ext4 filesystem being remounted at / supports timestamps until 2038 (0x7fffffff)".

Would you take a PR to change the default for 'small', protecting against the 2038 issue on these filesystems?

**Comment by jluebbe** [comment] 2022-03-18 13:13
@tytso Friendly ping. :) Do you have an opinion on this?

**Comment by tytso** [comment] 2022-03-19 23:03
The default was changed in v1.46.4, although there were some regression test failures resulting from this change that wasn't noticed before 1.46.4 got released, so I recommend that you go to v1.46.5.  So with the most recent released version of e2fsprogs, the default inode size is always 256 bytes --- except in the case of Hurd, since the GNU Hurd (in addition to not supporting 64-bit userspace) doesn't support 256 byte inodes, either.   If anyone cares about 2038 support in GNU Hurd, please feel free to contact the GNU Hurd folks directly.  :-)

In any case, this issue has been overtaken by events, so I'm closing this issue.   Apologies for not closing this issue earlier.

**Closed by tytso** 2022-03-19 23:03 UTC

**Comment by jluebbe** [comment] 2022-03-20 06:19
Thanks!
