### ISSUE TITLE
Using fuse2fs on macOS results in "Journal needs recovery"

### ISSUE THREAD

**Issue by phil-blain** [tytso/e2fsprogs#57] opened 2020-12-27 04:38 UTC
Hi @tytso,

I'm trying to use fuse2fs on macOS 10.11.6 (El Capitan). I have [macFUSE](https://osxfuse.github.io/) installed (formerly "osxfuse") and I followed the instructions in INSTALL to build, adding `export CPPFLAGS=-I/usr/local/include/osxfuse/` before running configure so that ` fuse.h` from macFUSE is found. The build completes successfully.

I receive errors when I try to mount my ext4 volume:
~~~bash
$ mkdir -p ~/mounts/linux
$ cd ~/Code/e2fsprogs/build/misc
$ ./fuse2fs -o ro /dev/disk1s2 ~/mounts/linux/
Mounting read-only.
/dev/disk1s2: Permission denied.
Please run e2fsck -fy /dev/disk1s2
$ sudo ./fuse2fs -o ro /dev/disk1s2 ~/mounts/linux/
Mounting read-only.
Journal needs recovery; running `e2fsck -E journal_only' is required.
~~~

That partition mounts fine using https://github.com/gerard/ext4fuse (`sudo ext4fuse /dev/disk1s2 ~/mounts/linux/ -o allow_other`), but that implementation seems to have issues (and is not really maintained) so I thought I would try this project...

**Comment by tytso** [comment] 2021-01-29 22:33
As the error message states, the file system has a journal that needs to be replayed/recovered.   What this means is that file system was not cleanly unmounted, and so there are metadata updates which are in the write-ahead journal, but have not necessarily been written to the file system.  The journal can be replayed either by mounting the file system on Linux, or by running e2fsck on the file system.    Pretty much any invocation of e2fsck will do.   "e2fsck -E journal_only /dev/disk1s2" will do the bare minimum of just replaying the write ahead log.   "e2fsck /dev/disk1s2" will replay the journal, and will do a full filesystem check if the file system is marked as corrupted and needing a full file system check.   "e2fsck -f /dev/disk1s2" will replay the journal if necessary, and then force a full file system check, whether the superblock has the flag indicating that there is a known problem with the file system.

If the ext4fuse program isn't checking the "needs_recovery" flag, that would be one of its apparently many other issues that it has.   The fact that fuse2fs is refusing to mount a file system that need recovery is working as intended.

**Comment by phil-blain** [comment] 2021-01-29 22:36
Thanks for these details. I indeed might have force-shutdown the last time I booted into Linux.

**Comment by tytso** [comment] 2021-01-31 14:58
Note that you can build e2fsck for MacOS, so you don't have to run e2fsck on Linux (although you certainly can).

Good luck!

**Closed by tytso** 2021-01-31 14:58 UTC
